package com.worldhero.model.enums;

public enum OnboardingStep {
    WELCOME,
    SUMMON_KNIGHT_REQUIRED,
    SUMMON_RANGER_REQUIRED,
    FIRST_EXPEDITION_REQUIRED,
    FIRST_EXPEDITION_RUNNING,
    FIRST_EXPEDITION_CLAIM_REQUIRED,
    THIRD_SUMMON_REQUIRED,
    COMPLETE
}
