import { ItemTemplate } from '../types/item.types';

export const STARTER_TEMPLATES: Record<string, ItemTemplate> = {
  // --- CHESTS ---
  chest_normal: {
    id: 'chest_normal',
    name: 'Normal Wooden Chest',
    description: 'Basic chest dropped by wild monsters. Contains common gear and crafting materials.',
    iconKey: 'chest_wooden',
    itemType: 'CHEST',
    slot: 'TALISMAN',
    requiredClass: null,
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: {},
    iLvlScalingFactor: 1.0,
  },

  // --- CRAFTING MATERIALS & FRAMES ---
  mat_ring_frame: {
    id: 'mat_ring_frame',
    name: 'Ring Frame',
    description: 'Precision molded alloy frame required to craft rings in the Forge.',
    iconKey: 'ring_frame',
    itemType: 'MATERIAL',
    slot: 'RING_1',
    requiredClass: null,
    baseRarity: 'UNCOMMON',
    elementalType: 'PHYSICAL',
    baseStats: {},
    iLvlScalingFactor: 1.0,
  },
  mat_talisman_frame: {
    id: 'mat_talisman_frame',
    name: 'Talisman Frame',
    description: 'Ancient etched relic frame used to craft celestial talismans and amulets.',
    iconKey: 'talisman_frame',
    itemType: 'MATERIAL',
    slot: 'TALISMAN',
    requiredClass: null,
    baseRarity: 'UNCOMMON',
    elementalType: 'PHYSICAL',
    baseStats: {},
    iLvlScalingFactor: 1.0,
  },
  mat_iron_ingot: {
    id: 'mat_iron_ingot',
    name: 'Refined Iron Ingot',
    description: 'High-density smelted iron used for forging swords, shields, and heavy armor.',
    iconKey: 'iron_ingot',
    itemType: 'MATERIAL',
    slot: 'MAIN_HAND',
    requiredClass: null,
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: {},
    iLvlScalingFactor: 1.0,
  },
  mat_leather_strip: {
    id: 'mat_leather_strip',
    name: 'Tanned Leather',
    description: 'Durable treated leather for crafting bows and light scouting armor.',
    iconKey: 'leather',
    itemType: 'MATERIAL',
    slot: 'ARMOR',
    requiredClass: null,
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: {},
    iLvlScalingFactor: 1.0,
  },

  // --- WARRIOR EQUIPMENT ---
  wpn_iron_sword: {
    id: 'wpn_iron_sword',
    name: 'Novice Iron Sword',
    description: 'Reliable basic blade forged for beginner vanguard warriors.',
    iconKey: 'sword_iron',
    itemType: 'EQUIPMENT',
    slot: 'MAIN_HAND',
    requiredClass: 'WARRIOR',
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { physAtk: 15 },
    iLvlScalingFactor: 1.0,
  },
  wpn_royal_claymore: {
    id: 'wpn_royal_claymore',
    name: 'Royal Claymore',
    description: 'Forged from tempered titan steel with molten edges.',
    iconKey: 'sword_claymore',
    itemType: 'EQUIPMENT',
    slot: 'MAIN_HAND',
    requiredClass: 'WARRIOR',
    baseRarity: 'RARE',
    elementalType: 'PHYSICAL',
    baseStats: { physAtk: 45, atkPercent: 3.0, elemDmgBonus: 4.0 },
    iLvlScalingFactor: 1.1,
  },
  wpn_excalibur: {
    id: 'wpn_excalibur',
    name: 'Holy Blade Excalibur',
    description: 'Legendary holy sword cleaving through darkness with divine light.',
    iconKey: 'sword_holy',
    itemType: 'EQUIPMENT',
    slot: 'MAIN_HAND',
    requiredClass: 'WARRIOR',
    baseRarity: 'LEGENDARY',
    elementalType: 'PHYSICAL',
    baseStats: { physAtk: 125, critRate: 8.0, critDmg: 20.0, lifeSteal: 5.0, atkPercent: 5.0 },
    iLvlScalingFactor: 1.25,
  },
  shd_iron_shield: {
    id: 'shd_iron_shield',
    name: 'Novice Iron Shield',
    description: 'Solid heavy shield deflecting physical blows.',
    iconKey: 'shield_iron',
    itemType: 'EQUIPMENT',
    slot: 'OFF_HAND',
    requiredClass: 'WARRIOR',
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { armor: 12, maxHp: 25 },
    iLvlScalingFactor: 1.0,
  },
  shd_aegis_bulwark: {
    id: 'shd_aegis_bulwark',
    name: 'Aegis Bulwark Shield',
    description: 'Mythical divine bulwark absorbing catastrophic incoming damage.',
    iconKey: 'shield_aegis',
    itemType: 'EQUIPMENT',
    slot: 'OFF_HAND',
    requiredClass: 'WARRIOR',
    baseRarity: 'EPIC',
    elementalType: 'PHYSICAL',
    baseStats: { armor: 65, maxHp: 150, dmgReduction: 4.0, hpRegen: 4.0 },
    iLvlScalingFactor: 1.2,
  },
  hlm_iron_helm: {
    id: 'hlm_iron_helm',
    name: 'Iron Guard Greathelm',
    description: 'Solid forged helmet shielding the skull from fatal blows.',
    iconKey: 'helm_iron',
    itemType: 'EQUIPMENT',
    slot: 'HELMET',
    requiredClass: 'WARRIOR',
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { armor: 8, maxHp: 15 },
    iLvlScalingFactor: 1.0,
  },
  arm_plate_chest: {
    id: 'arm_plate_chest',
    name: 'Iron Plate Cuirass',
    description: 'Heavy armor plating defending vital organs.',
    iconKey: 'armor_plate',
    itemType: 'EQUIPMENT',
    slot: 'ARMOR',
    requiredClass: 'WARRIOR',
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { armor: 15, maxHp: 30 },
    iLvlScalingFactor: 1.0,
  },
  pnt_iron_greaves: {
    id: 'pnt_iron_greaves',
    name: 'Iron Plate Greaves',
    description: 'Heavy greaves securing posture in battle.',
    iconKey: 'pants_iron',
    itemType: 'EQUIPMENT',
    slot: 'PANTS',
    requiredClass: 'WARRIOR',
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { armor: 10, maxHp: 20 },
    iLvlScalingFactor: 1.0,
  },
  bot_iron_boots: {
    id: 'bot_iron_boots',
    name: 'Iron Heavy Sabatons',
    description: 'Sturdy armored footwear ensuring grounded balance.',
    iconKey: 'boots_iron',
    itemType: 'EQUIPMENT',
    slot: 'BOOTS',
    requiredClass: 'WARRIOR',
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { armor: 6, physAtk: 2 },
    iLvlScalingFactor: 1.0,
  },

  // --- RANGER EQUIPMENT ---
  wpn_hunting_bow: {
    id: 'wpn_hunting_bow',
    name: 'Recurve Shortbow',
    description: 'Light bow built for swift ranged sniping.',
    iconKey: 'bow_recurve',
    itemType: 'EQUIPMENT',
    slot: 'MAIN_HAND',
    requiredClass: 'RANGER',
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { physAtk: 16, atkSpeed: 0.05 },
    iLvlScalingFactor: 1.0,
  },
  wpn_windrunner_bow: {
    id: 'wpn_windrunner_bow',
    name: 'Windrunner Greatbow',
    description: 'Fires razor-sharp gale arrows tearing through enemy formations.',
    iconKey: 'bow_wind',
    itemType: 'EQUIPMENT',
    slot: 'MAIN_HAND',
    requiredClass: 'RANGER',
    baseRarity: 'EPIC',
    elementalType: 'COLD',
    baseStats: { physAtk: 65, atkSpeed: 0.15, critRate: 5.0, critDmg: 12.0 },
    iLvlScalingFactor: 1.2,
  },
  wpn_phantom_quiver: {
    id: 'wpn_phantom_quiver',
    name: 'Leather Arrow Quiver',
    description: 'Enables rapid arrow reloading.',
    iconKey: 'quiver_leather',
    itemType: 'EQUIPMENT',
    slot: 'OFF_HAND',
    requiredClass: 'RANGER',
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { physAtk: 6 },
    iLvlScalingFactor: 1.0,
  },
  hlm_leather_cap: {
    id: 'hlm_leather_cap',
    name: 'Scout Leather Hood',
    description: 'Keeps focus sharp in dense forests.',
    iconKey: 'hood_leather',
    itemType: 'EQUIPMENT',
    slot: 'HELMET',
    requiredClass: 'RANGER',
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { armor: 5, maxHp: 12 },
    iLvlScalingFactor: 1.0,
  },
  arm_leather_vest: {
    id: 'arm_leather_vest',
    name: 'Scout Leather Tunic',
    description: 'Supple leather vest maximizing agility.',
    iconKey: 'tunic_leather',
    itemType: 'EQUIPMENT',
    slot: 'ARMOR',
    requiredClass: 'RANGER',
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { armor: 10, maxHp: 25 },
    iLvlScalingFactor: 1.0,
  },
  pnt_leather_pants: {
    id: 'pnt_leather_pants',
    name: 'Scout Leather Breeches',
    description: 'Flexible pants tailored for swift dodging.',
    iconKey: 'pants_leather',
    itemType: 'EQUIPMENT',
    slot: 'PANTS',
    requiredClass: 'RANGER',
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { armor: 7, maxHp: 18 },
    iLvlScalingFactor: 1.0,
  },
  bot_leather_boots: {
    id: 'bot_leather_boots',
    name: 'Scout Agile Boots',
    description: 'Silent steps allowing swift repositioning.',
    iconKey: 'boots_leather',
    itemType: 'EQUIPMENT',
    slot: 'BOOTS',
    requiredClass: 'RANGER',
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { armor: 4, physAtk: 2 },
    iLvlScalingFactor: 1.0,
  },

  // --- MAGE EQUIPMENT ---
  wpn_apprentice_wand: {
    id: 'wpn_apprentice_wand',
    name: 'Apprentice Ash Wand',
    description: 'Channels primal arcane fire bursts.',
    iconKey: 'wand_ash',
    itemType: 'EQUIPMENT',
    slot: 'MAIN_HAND',
    requiredClass: 'MAGE',
    baseRarity: 'COMMON',
    elementalType: 'FIRE',
    baseStats: { magicAtk: 18 },
    iLvlScalingFactor: 1.0,
  },
  wpn_fire_staff: {
    id: 'wpn_fire_staff',
    name: 'Serpent Fire Staff',
    description: 'Summons blazing inferno waves that incinerate enemy ranks.',
    iconKey: 'staff_fire',
    itemType: 'EQUIPMENT',
    slot: 'MAIN_HAND',
    requiredClass: 'MAGE',
    baseRarity: 'RARE',
    elementalType: 'FIRE',
    baseStats: { magicAtk: 45, atkPercent: 4.0, elemDmgBonus: 5.0 },
    iLvlScalingFactor: 1.15,
  },
  wpn_void_orb: {
    id: 'wpn_void_orb',
    name: 'Arcane Focus Orb',
    description: 'Focus crystal accelerating spell cooldowns.',
    iconKey: 'orb_arcane',
    itemType: 'EQUIPMENT',
    slot: 'OFF_HAND',
    requiredClass: 'MAGE',
    baseRarity: 'COMMON',
    elementalType: 'CHAOS',
    baseStats: { magicAtk: 8 },
    iLvlScalingFactor: 1.0,
  },
  hlm_mage_circlet: {
    id: 'hlm_mage_circlet',
    name: 'Apprentice Circlet',
    description: 'Focuses mental clarity.',
    iconKey: 'circlet_apprentice',
    itemType: 'EQUIPMENT',
    slot: 'HELMET',
    requiredClass: 'MAGE',
    baseRarity: 'COMMON',
    elementalType: 'FIRE',
    baseStats: { magicAtk: 3, armor: 3 },
    iLvlScalingFactor: 1.0,
  },
  arm_silk_robe: {
    id: 'arm_silk_robe',
    name: 'Arcane Silk Vestment',
    description: 'Woven with mana threads to absorb elemental recoil.',
    iconKey: 'robe_silk',
    itemType: 'EQUIPMENT',
    slot: 'ARMOR',
    requiredClass: 'MAGE',
    baseRarity: 'COMMON',
    elementalType: 'FIRE',
    baseStats: { magicAtk: 5, armor: 5, maxHp: 18 },
    iLvlScalingFactor: 1.0,
  },
  pnt_silk_pants: {
    id: 'pnt_silk_pants',
    name: 'Arcane Silk Skirt',
    description: 'Lightweight garments providing spell protection.',
    iconKey: 'pants_silk',
    itemType: 'EQUIPMENT',
    slot: 'PANTS',
    requiredClass: 'MAGE',
    baseRarity: 'COMMON',
    elementalType: 'FIRE',
    baseStats: { magicAtk: 3, armor: 4 },
    iLvlScalingFactor: 1.0,
  },
  bot_silk_slippers: {
    id: 'bot_silk_slippers',
    name: 'Arcane Soft Slippers',
    description: 'Silent footwear reducing mana friction.',
    iconKey: 'boots_silk',
    itemType: 'EQUIPMENT',
    slot: 'BOOTS',
    requiredClass: 'MAGE',
    baseRarity: 'COMMON',
    elementalType: 'FIRE',
    baseStats: { magicAtk: 2, armor: 3 },
    iLvlScalingFactor: 1.0,
  },

  // --- PRIEST EQUIPMENT ---
  wpn_holy_mace: {
    id: 'wpn_holy_mace',
    name: 'Acolyte Silver Mace',
    description: 'Blessed morningstar channeling restorative divine light.',
    iconKey: 'mace_silver',
    itemType: 'EQUIPMENT',
    slot: 'MAIN_HAND',
    requiredClass: 'PRIEST',
    baseRarity: 'COMMON',
    elementalType: 'LIGHTNING',
    baseStats: { magicAtk: 15, maxHp: 20 },
    iLvlScalingFactor: 1.0,
  },
  wpn_holy_bell: {
    id: 'wpn_holy_bell',
    name: 'Resonance Holy Chime',
    description: 'Restores squad vitality and erects protective holy shields.',
    iconKey: 'bell_holy',
    itemType: 'EQUIPMENT',
    slot: 'OFF_HAND',
    requiredClass: 'PRIEST',
    baseRarity: 'UNCOMMON',
    elementalType: 'CHAOS',
    baseStats: { magicAtk: 18, maxHp: 40 },
    iLvlScalingFactor: 1.1,
  },
  wpn_sacred_tome: {
    id: 'wpn_sacred_tome',
    name: 'Prayer Scripture Tome',
    description: 'Sacred verses protecting allies from harm.',
    iconKey: 'tome_prayer',
    itemType: 'EQUIPMENT',
    slot: 'OFF_HAND',
    requiredClass: 'PRIEST',
    baseRarity: 'COMMON',
    elementalType: 'LIGHTNING',
    baseStats: { magicAtk: 8, maxHp: 25 },
    iLvlScalingFactor: 1.0,
  },
  hlm_priest_miter: {
    id: 'hlm_priest_miter',
    name: 'Acolyte Holy Mitre',
    description: 'Blessed headdress providing protection.',
    iconKey: 'mitre_acolyte',
    itemType: 'EQUIPMENT',
    slot: 'HELMET',
    requiredClass: 'PRIEST',
    baseRarity: 'COMMON',
    elementalType: 'LIGHTNING',
    baseStats: { armor: 4, maxHp: 15 },
    iLvlScalingFactor: 1.0,
  },
  arm_priest_cassock: {
    id: 'arm_priest_cassock',
    name: 'Acolyte White Cassock',
    description: 'Holy vestment shielding against dark curses.',
    iconKey: 'cassock_white',
    itemType: 'EQUIPMENT',
    slot: 'ARMOR',
    requiredClass: 'PRIEST',
    baseRarity: 'COMMON',
    elementalType: 'LIGHTNING',
    baseStats: { armor: 8, maxHp: 35 },
    iLvlScalingFactor: 1.0,
  },
  pnt_priest_pants: {
    id: 'pnt_priest_pants',
    name: 'Acolyte White Robes',
    description: 'Comfortable clerical garments.',
    iconKey: 'pants_priest',
    itemType: 'EQUIPMENT',
    slot: 'PANTS',
    requiredClass: 'PRIEST',
    baseRarity: 'COMMON',
    elementalType: 'LIGHTNING',
    baseStats: { armor: 5, maxHp: 18 },
    iLvlScalingFactor: 1.0,
  },
  bot_priest_sandals: {
    id: 'bot_priest_sandals',
    name: 'Acolyte Pilgrim Sandals',
    description: 'Durable sandals blessed for holy crusades.',
    iconKey: 'sandals_pilgrim',
    itemType: 'EQUIPMENT',
    slot: 'BOOTS',
    requiredClass: 'PRIEST',
    baseRarity: 'COMMON',
    elementalType: 'LIGHTNING',
    baseStats: { armor: 3, maxHp: 12 },
    iLvlScalingFactor: 1.0,
  },

  // --- ACCESSORIES (Universal - Standardized to RING_1 and TALISMAN) ---
  acc_copper_ring: {
    id: 'acc_copper_ring',
    name: 'Polished Copper Ring',
    description: 'Simple copper band imbued with subtle vigor.',
    iconKey: 'ring_copper',
    itemType: 'ACCESSORY',
    slot: 'RING_1',
    requiredClass: null,
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { physAtk: 3, magicAtk: 3 },
    iLvlScalingFactor: 1.0,
  },
  acc_ruby_ring: {
    id: 'acc_ruby_ring',
    name: 'Ruby Battle Band',
    description: 'Empowers overall physical and magical attack power.',
    iconKey: 'ring_ruby',
    itemType: 'ACCESSORY',
    slot: 'RING_1',
    requiredClass: null,
    baseRarity: 'UNCOMMON',
    elementalType: 'PHYSICAL',
    baseStats: { physAtk: 6, magicAtk: 6, atkPercent: 2.0 },
    iLvlScalingFactor: 1.1,
  },
  acc_emerald_ring: {
    id: 'acc_emerald_ring',
    name: 'Emerald Signet Ring',
    description: 'Special ring boosting critical strike rate and speed.',
    iconKey: 'ring_emerald',
    itemType: 'ACCESSORY',
    slot: 'RING_1',
    requiredClass: null,
    baseRarity: 'RARE',
    elementalType: 'PHYSICAL',
    baseStats: { critRate: 3.0, critDmg: 6.0, atkSpeed: 0.03 },
    iLvlScalingFactor: 1.15,
  },
  acc_stone_talisman: {
    id: 'acc_stone_talisman',
    name: 'Ancient Stone Talisman',
    description: 'Weathered runic stone warding off dark energies.',
    iconKey: 'talisman_stone',
    itemType: 'ACCESSORY',
    slot: 'TALISMAN',
    requiredClass: null,
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { maxHp: 25, armor: 4 },
    iLvlScalingFactor: 1.0,
  },
  acc_wooden_amulet: {
    id: 'acc_wooden_amulet',
    name: 'Oak Tree Talisman',
    description: 'Carved oak talisman granting fortitude.',
    iconKey: 'amulet_oak',
    itemType: 'ACCESSORY',
    slot: 'TALISMAN',
    requiredClass: null,
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { maxHp: 30 },
    iLvlScalingFactor: 1.0,
  },

  // --- CRAFTING MATERIALS ---
  mat_iron_ore: {
    id: 'mat_iron_ore',
    name: 'Raw Iron Ore',
    description: 'Basic mineral extracted from mountain quarries, used for weapon crafting.',
    iconKey: 'ore_iron',
    itemType: 'MATERIAL',
    slot: 'TALISMAN',
    requiredClass: null,
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: {},
    iLvlScalingFactor: 1.0,
  },
  mat_beast_leather: {
    id: 'mat_beast_leather',
    name: 'Tough Beast Leather',
    description: 'Durable hides stripped from wild predators, used for armor tailoring.',
    iconKey: 'leather_beast',
    itemType: 'MATERIAL',
    slot: 'TALISMAN',
    requiredClass: null,
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: {},
    iLvlScalingFactor: 1.0,
  },
  mat_arcane_dust: {
    id: 'mat_arcane_dust',
    name: 'Glimmering Arcane Dust',
    description: 'Refined magical residue required for enchanting and transmutation.',
    iconKey: 'dust_arcane',
    itemType: 'MATERIAL',
    slot: 'TALISMAN',
    requiredClass: null,
    baseRarity: 'COMMON',
    elementalType: 'FIRE',
    baseStats: {},
    iLvlScalingFactor: 1.0,
  },

  // --- GEMS ---
  gem_ruby_t1: {
    id: 'gem_ruby_t1',
    name: 'Chipped Ruby (Tier 1)',
    description: 'Inlay into sockets to increase Physical ATK and Fire Damage.',
    iconKey: 'gem_ruby',
    itemType: 'GEM',
    slot: 'TALISMAN',
    requiredClass: null,
    baseRarity: 'COMMON',
    elementalType: 'FIRE',
    baseStats: { physAtk: 6, elemDmgBonus: 2.0 },
    iLvlScalingFactor: 1.0,
  },
  gem_emerald_t1: {
    id: 'gem_emerald_t1',
    name: 'Chipped Emerald (Tier 1)',
    description: 'Inlay into sockets to increase Attack Speed and Critical Rate.',
    iconKey: 'gem_emerald',
    itemType: 'GEM',
    slot: 'TALISMAN',
    requiredClass: null,
    baseRarity: 'COMMON',
    elementalType: 'PHYSICAL',
    baseStats: { atkSpeed: 0.05, critRate: 1.5 },
    iLvlScalingFactor: 1.0,
  },
  gem_sapphire_t1: {
    id: 'gem_sapphire_t1',
    name: 'Chipped Sapphire (Tier 1)',
    description: 'Inlay into sockets to increase Magic ATK and Max HP.',
    iconKey: 'gem_sapphire',
    itemType: 'GEM',
    slot: 'TALISMAN',
    requiredClass: null,
    baseRarity: 'COMMON',
    elementalType: 'COLD',
    baseStats: { magicAtk: 6, maxHp: 25 },
    iLvlScalingFactor: 1.0,
  },
};
